apiVersion: v1  # Specifies the API version for the ConfigMap resource. 'v1' 
kind: ConfigMap  # Declares that this resource is a ConfigMap
metadata:
  name: prab-config  # The name of the ConfigMap. 
  namespace: {{ .Values.namespace }}  # The Kubernetes namespace where the ConfigMap will be created. 
data:
  PORTXXX: "{{ .Values.appPort }}"  # A key-value pair stored in the ConfigMap. 'PORTXXX' is the key
  TEXTXXX: {{ .Values.appText }}  # Another key-value pair. 'TEXTXXX' is the key.