name: Build/Push prabkang/prab-test

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: Docker

    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: Login to Harbor
        uses: docker/login-action@v3
        with:
          registry: harbor.byhiras.co.uk
          username: ${{ secrets.SYSTEMS_HARBOR_USERNAME  }}
          password: ${{ secrets.SYSTEMS_HARBOR_PASSWORD }}

      - uses: actions/checkout@v3
      - name: Build and Push Image to Harbor
        run: |
          docker build -f server/Dockerfile . -t harbor.byhiras.co.uk/legacy-container-registry/prabkang/prab-test:${{ github.run_number }}
          docker push harbor.byhiras.co.uk/legacy-container-registry/prabkang/prab-test:${{ github.run_number }}
          docker build -f client/Dockerfile . -t harbor.byhiras.co.uk/legacy-container-registry/prabkang/prab-test:${{ github.run_number }}
          docker push harbor.byhiras.co.uk/legacy-container-registry/prabkang/prab-test:${{ github.run_number }}




